LIST P = 16F887
#INCLUDE <p16F887.inc>

; CONFIG1
; __config 0xFFE1
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF


; DEFINICION DE REGISTROS

AUX_K		EQU	0x20	
CONT_K		EQU	0x21
KEY			EQU	0x22
AUX_INT		EQU	0x23
W_AUX		EQU	0x24
ST_AUX		EQU	0x25
CONT_T		EQU	0x26
CONTS_T		EQU	0x27
CONT_1		EQU	0x28
CONT_2		EQU	0x29

			ORG 0x00	
			GOTO	INICIO

			ORG 0x04
			GOTO	INTRP
				

		
INICIO
			CALL		CONF
			CLRF		CONTS_T
		;	CLRF		KEY
			MOVLW		0xF7			;0   1111 0111 -> COSAS RARAS PASAN,
			MOVWF		AUX_K			;DEBERIA ANDAR PERO COMO NO COMENTE NO
			BSF			INTCON, 7			;VOY A ENTENDER NADA DESPUES



LOOP		
			CALL		SAVE_ENV
			MOVF		CONTS_T, 0;		MOSTRAMOS EN DISPLAY
			CALL 		DISPLAY
			MOVWF		PORTD
			CALL		LOAD_ENV
		
			MOVF		AUX_K, 0		;YA NO SE “”””DEBERIA”””” ROMPER
			MOVWF		PORTB
			
			RLF			AUX_K, 1
			
			;MOVF		CONTS_T, 1
			;BTFSS		STATUS, Z
			GOTO		LOOP

		

INTRP
			CALL		SAVE_ENV
	
			BTFSC		INTCON, 0
			CALL		TECLA		

			;BTFSC		INTCON, 2
			;CALL 		TIMER
			
			CALL		LOAD_ENV
			
			RETFIE


TECLA
		;	MOVF		KEY,0
		;	BTFSS		STATUS,Z	
		;	RETURN 			
			
			CALL 		RETARDO			

			BANKSEL		PORTB		

			CLRF		CONT_K		
	
			CLRF		KEY		

			;COLUMNAS
			
			MOVLW		0x00		

			BTFSS		PORTB, 3
			MOVWF		CONT_K
			ADDLW		0x01		

			BTFSS		PORTB, 0
			MOVWF		CONT_K
			ADDLW		0x01
			
			BTFSS		PORTB, 1
			MOVWF		CONT_K
			ADDLW		0x01		

			BTFSS		PORTB, 2
			MOVWF		CONT_K		

	
			MOVF		CONT_K, 0
			
			;FILAS
			
	COLUMNAS		
			BTFSS		PORTB, 4
			MOVWF		KEY
			
			ADDLW		0x03
			BTFSS		PORTB, 5
			MOVWF		KEY
			
			ADDLW		0x03
			BTFSS		PORTB, 6
			MOVWF		KEY
			
			ADDLW		0x03
			BTFSS		PORTB, 7
			MOVWF		KEY
			
			BCF			INTCON, RBIF		

			;MOVLW		.62			;HABILITAMOS EL TIMER0
		;	MOVWF		TMR0
		;	BCF			INTCON, 2
		;	BSF			INTCON, 5
		;	
			MOVF		KEY, 0;		PONEMOS EL VALOR DE KEY EN CONT_S
			BTFSS		STATUS, Z
			MOVWF		CONTS_T		

			RETURN


SAVE_ENV
			MOVWF		W_AUX
			SWAPF		STATUS, 0
			MOVWF		ST_AUX
	
			RETURN
	

LOAD_ENV
			SWAPF		ST_AUX, 0
			MOVWF		STATUS
			SWAPF		W_AUX, 1
			SWAPF		W_AUX, 0
			
			RETURN
			
DISPLAY
	ADDWF		PCL,1
	RETLW		0x7E;b’0111 1110’;			CERO
	RETLW		0x30;b’0011 0000’;			UNO
	RETLW		0x6D;b’0110 1101’;			DOS	
	RETLW		0x79;b’0111 1001’;			TRES	
	RETLW		0x33;b’0011 0011’;			CUATRO
	RETLW		0x5B;b’0101 1011’;			CINCO
	RETLW		0x5F;b’0101 1111’;			SEIS	
	RETLW		0x70;b’0111 0000’;			SIETE
	RETLW		0x7F;b’0111 1111’;			OCHO
	RETLW		0x7B;b’0111 1011’;			NUEVE

CONF
	BANKSEL	OPTION_REG
	MOVLW		0x07
	MOVWF		OPTION_REG
	
	BANKSEL	WPUB
	MOVLW		0xF0
	MOVWF		WPUB
	
	BANKSEL	INTCON;		CAMBIAR ESTO PARA TMR0
	MOVLW		0x08
	MOVWF		INTCON
	
	BANKSEL	IOCB
	MOVLW		0xF0
	MOVWF		IOCB
	
	BANKSEL	ANSEL
	CLRF		ANSEL
	CLRF		ANSELH
	
	BANKSEL	PORTB
	CLRF		PORTB
	
	BANKSEL	TRISB
	MOVLW		0xF0
	MOVWF		TRISB

	BANKSEL	PORTD
	CLRF		PORTD

	BANKSEL	TRISD
	CLRF		TRISD;				TODAS SALIDAS
	
	BCF		STATUS, RP1
	BCF		STATUS, RP0
	
	RETURN


RETARDO
	
	MOVLW		0x2F
	MOVWF		CONT_2
LOOP2	MOVLW		0xFF
	MOVWF		CONT_1
LOOP1	DECFSZ		CONT_1, 1
	GOTO		LOOP1
	DECFSZ		CONT_2, 1
	GOTO		LOOP2
	RETURN

	END