List p = 16f887
Include <p16f887.inc>
	
AUX_K		EQU	0x20	
CONT_K		EQU	0x21
KEY		EQU	0x22
AUX_INT		EQU	0x23
W_AUX		EQU	0x24
ST_AUX		EQU	0x25
CONT_T		EQU	0x26
CONTS_T		EQU	0x27
CONT_1		EQU	0x28
CONT_2		EQU	0x29
	
		ORG	0x00
		GOTO	INICIO

		ORG	0x04
		GOTO	INTRP
	
	
INICIO
	CALL		CONF
	
	MOVLW		0xF7			;0   1111 0111 -> COSAS RARAS PASAN,
	MOVWF		AUX_K			;DEBERIA ANDAR PERO COMO NO COMENTE NO
						;VOY A ENTENDER NADA DESPUES

LOOP		
	MOVF		CONTS_T, 0;		MOSTRAMOS EN DISPLAY
	CALL 		DISPLAY
	MOVWF		PORTA

	MOVF		AUX_K, 0		;YA NO SE “”””DEBERIA”””” ROMPER
	MOVWF		PORTB
	BCF		INTCON, 0		;GUALICHO.START()
	BSF		INTCON, 3
	
	INCF		CONT_K, 0		;MAGIA NEGRA
	ANDLW		0x03
	
	BCF		INTCON, 3		;GUALICHO.END()
	MOVWF		CONT_K
	
	RLF		AUX_K, 1
	
	MOVF		CONTS_T, 1
	BTFSS		STATUS, Z
	GOTO		LOOP
	
	;ENVIO A RB

	MOVF		PORTA, 0
	BSF		PORTA, 7
	CALL		RETARDO
	BCF		PORTA, 7
	GOTO		LOOP

INTRP
	CALL		SAVE_ENV
	
	BTFSC		INTCON, 0
	CALL		TECLA

	BTFSC		INTCON, 2
	CALL 		TIMER
	
	CALL		LOAD_ENV
	
	RETFIE
	

TECLA
	CALL 		RETARDO

	BANKSEL		PORTB
	MOVF		CONT_K, 0
	
	BTFSS		PORTB, 4
	MOVWF		KEY
	
	ADDLW		0x03
	BTFSS		PORTB, 5
	MOVWF		KEY
	
	ADDLW		0x03
	BTFSS		PORTB, 6
	MOVWF		KEY
	
	ADDLW		0x03
	BTFSS		PORTB, 7
	MOVWF		KEY
	
	BCF		INTCON, RBIF

	MOVLW		.62			;HABILITAMOS EL TIMER0
	MOVWF		TMR0
	BCF		INTCON, 2
	BSF		INTCON, 5
	
	MOVF		KEY, 0;		PONEMOS EL VALOR DE KEY EN CONT_S
	MOVWF		CONTS_T

	RETURN
	
	
SAVE_ENV
	MOVWF		W_AUX
	SWAPF		STATUS, 0
	MOVWF		ST_AUX
	
	RETURN
	

LOAD_ENV
	SWAPF		ST_AUX, 0
	MOVWF		STATUS
	SWAPF		W_AUX, 1
	SWAPF		W_AUX, 0
	
	RETURN


TIMER
	BCF		INTCON,2;	BAJAR BANDERA DE INTERRUPCIONES DE TMR0		
	MOVLW		.62;		VALOR A ASIGNAR DEL TMR0 PARA 50MS
	MOVWF		TMR0;		MOVER AL REG TMR0
	DECFSZ		CONT_T,1;
	RETURN

	MOVLW		0x14;		PONER CONT EN 20
	MOVWF		CONT_T;
	DECFSZ		CONTS_T,1;
	RETURN

	
	
CONF
	BANKSEL		OPTION_REG
	MOVLW		0x07
	MOVWF		OPTION_REG
	
	BANKSEL		WPUB
	MOVLW		0xF0
	MOVWF		WPUB
		
	BANKSEL		INTCON;		CAMBIAR ESTO PARA TMR0
	MOVLW		0x08
	MOVWF		INTCON
	
	BANKSEL		IOCB
	MOVLW		0xF0
	MOVWF		IOCB
	
	BANKSEL		ANSEL
	CLRF		ANSEL
	CLRF		ANSELH
	
	BANKSEL		PORTB
	CLRF		PORTB
	
	BANKSEL		TRISB
	MOVLW		0xF0
	MOVWF		TRISB

	BANKSEL		PORTA
	CLRF		PORTA

	BANKSEL		TRISA
	CLRF		TRISA;				TODAS SALIDAS
	
	BCF		STATUS, RP1
	BCF		STATUS, RP0
	
	RETURN
	
	
	END

DISPLAY
	ADDWF		PCL,1
	RETLW		b’01111110’;			CERO
	RETLW		b’00110000’;			UNO
	RETLW		b’01101101’;			DOS	
	RETLW		b’01111001’;			TRES	
	RETLW		b’00110011’;			CUATRO
	RETLW		b’01011011’;			CINCO
	RETLW		b’01011111’;			SEIS	
	RETLW		b’01110000’;			SIETE
	RETLW		b’01111111’;			OCHO
	RETLW		b’01111011’;			NUEVE


RETARDO
	
	MOVLW		0x04
	MOVWF		CONT_2
LOOP2	MOVLW		0xFF
	MOVWF		CONT_1
LOOP1	DECFSZ		CONT_1, 1
	GOTO		LOOP1
	DECFSZ		CONT_2, 1
	GOTO		LOOP2
	RETURN
