LIST P = 16F887
#INCLUDE <p16F887.inc>

; CONFIG1
; __config 0xFFE1
 __CONFIG _CONFIG1, _FOSC_INTRC_CLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2

; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF


; DEFINICION DE REGISTROS

AUX_K		EQU	0x20	
PORTB_AUX	EQU	0x30
KEY			EQU	0x22
AUX_INT		EQU	0x23
W_AUX		EQU	0x24
ST_AUX		EQU	0x25
CONT_T		EQU	0x26
CONTS_T		EQU	0x27
CONT_1		EQU	0x28
CONT_2		EQU	0x29

			ORG 0x00	
			GOTO	INICIO

			ORG 0x04
			GOTO	INTRP
				

		
INICIO
			CLRF		W
			CLRF		STATUS
			CLRF		AUX_K
			CLRF		PORTB_AUX
			CLRF		KEY
			CLRF		AUX_INT
			CLRF		W_AUX
			CLRF		ST_AUX
			CLRF		CONT_T
			CLRF		CONTS_T
			CLRF		CONT_1
			CLRF		CONT_2
			
			CALL		CONF

			MOVLW		0xF7			;0   1111 0111 -> COSAS RARAS PASAN,
			MOVWF		AUX_K			;DEBERIA ANDAR PERO COMO NO COMENTE NO
			BSF			INTCON, 7			;VOY A ENTENDER NADA DESPUES



LOOP		
			CALL		SAVE_ENV
			MOVF		CONTS_T, 0;		MOSTRAMOS EN DISPLAY
			CALL 		DISPLAY
			MOVWF		PORTD
			CALL		LOAD_ENV
		
			MOVF		AUX_K, 0		
			MOVWF		PORTB
			BCF			INTCON,3
			CALL		RETARDO2
			BCF			INTCON,0
			BSF			INTCON,3
			
			RLF			AUX_K, 1
;			CALL		RETARDO2

			GOTO		LOOP

		

INTRP

			CALL		SAVE_ENV
	
			BTFSC		INTCON, 0
			CALL		TECLA		

			BTFSC		INTCON, 2
			CALL 		TIMER
			
			CALL		LOAD_ENV
			
			RETFIE


TECLA		
			
			CALL 		RETARDO			
			

			BANKSEL		PORTB
			MOVF		PORTB,0
			MOVWF		PORTB_AUX		
		
	
			CLRF		KEY		

			;COLUMNAS
			MOVLW		0x00		

			BTFSS		PORTB_AUX, 0
			MOVLW		0x01
			BTFSS		PORTB_AUX, 1
			MOVLW		0x02
			BTFSS		PORTB_AUX, 2
			MOVLW		0x03

			
	COLUMNAS		
			BTFSS		PORTB_AUX, 4
			MOVWF		KEY
			
			ADDLW		0x03
			BTFSS		PORTB_AUX, 5
			MOVWF		KEY
			
			ADDLW		0x03
			BTFSS		PORTB_AUX, 6
			MOVWF		KEY
			
			ADDLW		0x03
			BTFSS		PORTB_AUX, 7
			MOVWF		KEY
			
			BCF			INTCON, RBIF
			
			;CALL		RETARDO2		
			;MOVLW		0x14
			;MOVWF		CONT_T
			;CALL		RETARDO2
			
			MOVLW		.62			;HABILITAMOS EL TIMER0
			MOVWF		TMR0
			BCF			INTCON, 2
			BSF			INTCON, 5
			
			BSF			PORTA,1		;BOMB HAS BEEN PLANTED
			CALL		RETARDO
			
			MOVF		KEY, 0;		PONEMOS EL VALOR DE KEY EN CONT_S
			BTFSS		STATUS, Z
			MOVWF		CONTS_T		

			RETURN

TIMER
			BCF			INTCON,2;	BAJAR BANDERA DE INTERRUPCIONES DE TMR0		
			MOVLW		.62;		VALOR A ASIGNAR DEL TMR0 PARA 50MS
			MOVWF		TMR0;		MOVER AL REG TMR0
			DECFSZ		CONT_T,1;
			RETURN
		
			BSF			PORTA,0
			CALL		RETARDO
			CALL		RETARDO
			BCF			PORTA,0
			
			MOVLW		0x14;		PONER CONT EN 20
			MOVWF		CONT_T;
			DECFSZ		CONTS_T,1;
			RETURN
			BCF			INTCON,5
			
			BCF			PORTA, 1	;Terrorists win
			
			
			RETURN

SAVE_ENV
			MOVWF		W_AUX
			SWAPF		STATUS, 0
			MOVWF		ST_AUX
	
			RETURN
	

LOAD_ENV
			SWAPF		ST_AUX, 0
			MOVWF		STATUS
			SWAPF		W_AUX, 1
			SWAPF		W_AUX, 0
			
			RETURN
		
		
DISPLAY
	ADDWF		PCL,1
	RETLW		0x7E;b’0111 1110’;			CERO
	RETLW		0x30;b’0011 0000’;			UNO
	RETLW		0x6D;b’0110 1101’;			DOS	
	RETLW		0x79;b’0111 1001’;			TRES	
	RETLW		0x33;b’0011 0011’;			CUATRO
	RETLW		0x5B;b’0101 1011’;			CINCO
	RETLW		0x5F;b’0101 1111’;			SEIS	
	RETLW		0x70;b’0111 0000’;			SIETE
	RETLW		0x7F;b’0111 1111’;			OCHO
	RETLW		0x7B;b’0111 1011’;			NUEVE

CONF
	BANKSEL	OPTION_REG
	MOVLW		0x07
	MOVWF		OPTION_REG
	
	BANKSEL	WPUB
	MOVLW		0xF0
	MOVWF		WPUB
	
	BANKSEL	INTCON;		CAMBIAR ESTO PARA TMR0
	MOVLW		0x08
	MOVWF		INTCON
	
	BANKSEL	IOCB
	MOVLW		0xF0
	MOVWF		IOCB
	
	BANKSEL	ANSEL
	CLRF		ANSEL
	CLRF		ANSELH
	
	BANKSEL	PORTB
	CLRF		PORTB
	
	BANKSEL	TRISB
	MOVLW		0xF0
	MOVWF		TRISB

	BANKSEL	PORTD
	CLRF		PORTD
	
	BANKSEL	PORTA
	CLRF		PORTA
	
	BANKSEL TRISA
	BCF			TRISA, 1
	BCF			TRISA, 0

	BANKSEL	TRISD
	CLRF		TRISD;				TODAS SALIDAS
	
	BCF		STATUS, RP1
	BCF		STATUS, RP0
	
	RETURN


RETARDO
	
	MOVLW		0x1F
	MOVWF		CONT_2
LOOP2	MOVLW		0xFF
	MOVWF		CONT_1
LOOP1	DECFSZ		CONT_1, 1
	GOTO		LOOP1
	DECFSZ		CONT_2, 1
	GOTO		LOOP2
	RETURN

RETARDO2
	
	MOVLW		0x04
	MOVWF		CONT_2
LOOP3	MOVLW		0xFF
	MOVWF		CONT_1
LOOP4	DECFSZ		CONT_1, 1
	GOTO		LOOP4
	DECFSZ		CONT_2, 1
	GOTO		LOOP3
	RETURN



	END